[mgr]
ratio = [1, 2, 5]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
show_symlink = true
linemode = "size"
show_hidden = true
mouse_events = ["click", "scroll"]

[opener]
edit = [
    { run = 'nvim "$@"', desc = "nvim", block = true, for = "unix" },
    { run = 'code %*', orphan = true, desc = "code", for = "windows" },
    { run = 'code -w %*', block = true, desc = "code (block)", for = "windows" },
]
play = [
    { run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
    { run = 'mpv --force-window %*', orphan = true, for = "windows" },
    { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]